<a href="https://colab.research.google.com/github/Crowk999/Pytorch_Learning/blob/main/Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
import pandas as pd
print(torch.__version__)

2.10.0+cpu


### Random Tesnor

### Random tensor is important beacuse our neural network start with random tensor then adjust those random number to provide the meaningful output.

In [ ]:
# random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4496, 0.7280, 0.6998, 0.1725],
        [0.8906, 0.9186, 0.8780, 0.2243],
        [0.2176, 0.0213, 0.5425, 0.7008]])

In [ ]:
random_image_size = torch.rand(size=(240,240,3)) # Height Width Channel
random_image_size.shape, random_image_size.ndim


(torch.Size([240, 240, 3]), 3)

In [ ]:
# Zero Tensors
zero_tensor = torch.zeros((1,2,3))
# One Tensors
one_tensors = torch.ones((1,2,3))
#print
one_tensors, zero_tensor

(tensor([[[1., 1., 1.],
          [1., 1., 1.]]]),
 tensor([[[0., 0., 0.],
          [0., 0., 0.]]]))