<a href="https://colab.research.google.com/github/Crowk999/Pytorch_Learning/blob/main/Basics_part2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
import pandas as pd
print(torch.__version__)

In [ ]:
A = torch.tensor([1,2,3,4])
B = torch.tensor(5)
B

tensor(5)

### Random Tesnor

### Random tensor is important beacuse our neural network start with random tensor then adjust those random number to provide the meaningful output.

In [ ]:
# random tensor of size (3,4) that also in minus
random_tensor = -torch.rand(3,4)
random_tensor

tensor([[-0.8696, -0.9914, -0.6801, -0.3139],
        [-0.7273, -0.3153, -0.6707, -0.8604],
        [-0.6159, -0.8221, -0.5790, -0.7165]])

In [ ]:
random_image_size = torch.rand(size=(240,240,3)) # Height Width Channel
random_image_size.shape, random_image_size.ndim


In [ ]:
# Zero Tensors
zero_tensor = torch.zeros((1,2,3))
# One Tensors
one_tensors = torch.ones((1,2,3))
#print
one_tensors, zero_tensor

(tensor([[[1., 1., 1.],
          [1., 1., 1.]]]),
 tensor([[[0., 0., 0.],
          [0., 0., 0.]]]))

In [ ]:
# Creating range
one_to_ten = torch.arange(10,0,-5)
one_to_ten


tensor([10,  5])

In [ ]:
ten_zeros = torch.ones_like(one_to_ten)
ten_zeros

tensor([1, 1])

In [ ]:
data_type_32 = torch.tensor([1,2,3],
                            dtype=torch.int32,
                            device=None,
                            requires_grad=False)
data_type_32.dtype

torch.int32

In [ ]:
data_type_16 = data_type_32.type(torch.float16)
print(data_type_32*data_type_16)

DERIVATION

In [ ]:
#derivation
x = torch.tensor(2.0, requires_grad=True)
y = x**2
y.backward(x)
x.grad

GETTING INFORMATION FROM TENSOR

In [ ]:
some_tensor = torch.randint(0,10,(3,4), device="cpu", dtype=torch.int16)
# details of this tensor:
print("The tensor itself:-",some_tensor)
print("The datatype of tensor:-", some_tensor.dtype)
print("The size of tensor:-", some_tensor.shape) # or tensor.size()
print("The device tensor on:-", some_tensor.device)
print("The dimension of tensor", some_tensor.ndim)

The tensor itself:- tensor([[7, 6, 7, 9],
        [6, 5, 1, 6],
        [4, 1, 9, 9]], dtype=torch.int16)
The datatype of tensor:- torch.int16
The size of tensor:- torch.Size([3, 4])
The device tensor on:- cpu
The dimension of tensor 2


In [ ]:
any_neg_float = ((torch.rand(5)*(50-10))+10)
positive_num = torch.randint(1,100,(2,5))
any_neg_float, positive_num

(tensor([28.4088, 29.7506, 40.2160, 17.6555, 13.2073]),
 tensor([[60, 57, 10, 75, 58],
         [33, 15, 82, 36,  7]]))